# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels_presence', '0001_initial'),
        ('chatdemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels_presence.Room'),
            preserve_default=False,
        ),
    ]
